<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto

namespace Cls\Log;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cls.Log.Content</code>
 */
class Content extends \Google\Protobuf\Internal\Message
{
    /**
     * 每组字段的 key
     *
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * 每组字段的 value
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @type string $key
     *           每组字段的 key
     * @type string $value
     *           每组字段的 value
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Cls::initOnce();
        parent::__construct($data);
    }

    /**
     * 每组字段的 key
     *
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * 每组字段的 key
     *
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * 每组字段的 value
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * 每组字段的 value
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Content::class, \Cls\Log_Content::class);

