<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto

namespace GPBMetadata;

class Cls
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        // 换行没有任何含义，只是为了好看，原生成的代码有特殊符号，gitee不支持
        $pool->internalAddGeneratedFile(hex2bin(
                '0a84030a09636c732e70726f746f1203636c73225e0a034c6f67120c0a047469' .
                '6d6518012001280312220a08636f6e74656e747318022003280b32102e636c73' .
                '2e4c6f672e436f6e74656e741a250a07436f6e74656e74120b0a036b657918012' .
                '0012809120d0a0576616c756518022001280922240a064c6f67546167120b0a03' .
                '6b6579180120012809120d0a0576616c756518022001280922ae010a084c6f674772' .
                '6f757012160a046c6f677318012003280b32082e636c732e4c6f6712180a0b636f6e74' .
                '657874466c6f77180220012809480088010112150a0866696c656e616d65180320012809' .
                '480188010112130a06736f757263651804200128094802880101121c0a076c6f6754616773' .
                '18052003280b320b2e636c732e4c6f67546167420e0a0c5f636f6e74657874466c6f77420' .
                'b0a095f66696c656e616d6542090a075f736f7572636522330a0c4c6f6747726f75704c6' .
                '9737412230a0c6c6f6747726f75704c69737418012003280b320d2e636c732e4c6f' .
                '6747726f7570620670726f746f33')
            , true);

        static::$is_initialized = true;
    }
}

